baseURL = "https://girlscript.xyz"
languageCode = "en-us"
title = "GirlScript Guwahati"

theme = "bittersteel"

[markup]
[markup.tableOfContents]
endLevel = 6
ordered = false
startLevel = 1

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
style = "friendly"
tabWidth = 4
